// P2.4 — the Noise handshake, against somebody else's implementation.
//
// The first test in this file is the one that matters. A Noise implementation
// that only ever talks to itself agrees with itself perfectly while being wrong
// in ways no round trip can reveal: HKDF arguments swapped, BLAKE2s's native
// keyed mode used where HMAC is specified, the nonce encoded big-endian, the
// ciphertext hashed instead of the plaintext. Every one of those produces a
// self-consistent private protocol with none of the review the real one has had.
//
// tests/vectors/NoiseVectors.h holds the official cross-implementation vectors
// for exactly the two protocols AirUSB speaks, generated by an independent
// implementation. Matching them message by message — including the final
// handshake hash, which is what the SAS is derived from — is what makes this a
// Noise implementation rather than something Noise-shaped.
//
// Everything after that tests the properties the vectors cannot: that tampering
// is caught, that a forged record does not desynchronise the stream, that the
// prologue is really bound, and that a truncated handshake message is refused
// rather than read past.

#include "../TestHarness.h"
#include "../vectors/NoiseVectors.h"
#include "../../protocol/Noise.h"
#include "../../crypto/Primitives.h"

#include <cstring>
#include <string>

using namespace airusb;
using namespace airusb::crypto;
using namespace airusb::protocol;
using namespace airusb::test::noisevec;

namespace {

std::vector<std::uint8_t> hx(const char* hex)
{
    std::vector<std::uint8_t> v;
    if (hex && !fromHex(hex, v)) {
        std::printf("\n    BAD HEX: %s\n", hex);
        std::abort();
    }
    return v;
}

SecretKey secretOf(const char* hex)
{
    const auto v = hx(hex);
    SecretKey k{};
    if (v.size() == k.size()) std::memcpy(k.data(), v.data(), k.size());
    return k;
}

PublicKey publicOf(const char* hex)
{
    const auto v = hx(hex);
    PublicKey k{};
    if (v.size() == k.size()) std::memcpy(k.data(), v.data(), k.size());
    return k;
}

std::size_t handshakeMessageCount(const char* protocolName)
{
    // XX is three messages, IK is two. Read from the name so a vector for some
    // other pattern cannot be silently mis-driven.
    return std::strstr(protocolName, "_IK_") ? 2u : 3u;
}

// ---------------------------------------------------------------------------
// THE test: replay the official vectors
// ---------------------------------------------------------------------------

void testOfficialVectors()
{
    std::printf("official Noise vectors (independent implementation)\n");

    CHECK(kVectorCount == 2);

    for (unsigned vi = 0; vi < kVectorCount; ++vi) {
        const Vector& v = kVectors[vi];

        TEST_CASE(v.protocolName) {
            const bool isIk = std::strstr(v.protocolName, "_IK_") != nullptr;
            const NoisePattern pattern = isIk ? NoisePattern::IK : NoisePattern::XX;

            // The vectors use the same prologue on both sides; assert it rather
            // than assume it, because a differing prologue is a legitimate
            // vector shape our driver would silently mishandle.
            CHECK(std::strcmp(v.initPrologue, v.respPrologue) == 0);

            HandshakeState init, resp;

            HandshakeState::Params ip;
            ip.pattern     = pattern;
            ip.initiator   = true;
            ip.prologue    = hx(v.initPrologue);
            ip.localStatic = secretOf(v.initStatic);
            if (isIk) {
                CHECK(v.initRemoteStatic != nullptr);
                ip.remoteStatic    = publicOf(v.initRemoteStatic);
                ip.hasRemoteStatic = true;
            }
            CHECK(init.start(ip) == Status::Ok);
            CHECK(init.setFixedEphemeralForTestingOnly(secretOf(v.initEphemeral)) == Status::Ok);

            HandshakeState::Params rp;
            rp.pattern     = pattern;
            rp.initiator   = false;
            rp.prologue    = hx(v.respPrologue);
            rp.localStatic = secretOf(v.respStatic);
            CHECK(resp.start(rp) == Status::Ok);
            CHECK(resp.setFixedEphemeralForTestingOnly(secretOf(v.respEphemeral)) == Status::Ok);

            // For IK the initiator's pre-shared remote static must be the
            // responder's actual static, or the vector itself is inconsistent.
            if (isIk) {
                const PublicKey respPub = x25519PublicKey(secretOf(v.respStatic));
                CHECK(toHex(respPub) == toHex(publicOf(v.initRemoteStatic)));
            }

            const std::size_t hsCount = handshakeMessageCount(v.protocolName);
            CHECK(v.messageCount > hsCount);

            // ---- handshake messages ------------------------------------------
            for (std::size_t i = 0; i < hsCount; ++i) {
                HandshakeState& sender   = (i % 2 == 0) ? init : resp;
                HandshakeState& receiver = (i % 2 == 0) ? resp : init;

                const auto payload  = hx(v.messages[i].payload);
                const auto expected = hx(v.messages[i].ciphertext);

                std::vector<std::uint8_t> produced;
                CHECK(sender.writeMessage(payload, produced) == Status::Ok);

                // Byte for byte against an implementation that is not ours.
                if (toHex(produced) != v.messages[i].ciphertext) {
                    std::printf("\n    message %zu mismatch\n      got  %s\n      want %s\n",
                                i, toHex(produced).c_str(), v.messages[i].ciphertext);
                }
                CHECK(toHex(produced) == std::string(v.messages[i].ciphertext));

                std::vector<std::uint8_t> got;
                CHECK(receiver.readMessage(expected, got) == Status::Ok);
                CHECK(got == payload);
            }

            CHECK(init.complete());
            CHECK(resp.complete());

            // ---- the channel binding ------------------------------------------
            //
            // This is the value the SAS is derived from. If it disagreed with the
            // reference, two AirUSB peers would still show each other matching
            // digits while binding to a transcript nobody else computes.
            CHECK(toHex(init.handshakeHash()) == std::string(v.handshakeHash));
            CHECK(toHex(resp.handshakeHash()) == std::string(v.handshakeHash));

            // Both sides learn the other's static key.
            CHECK(init.haveRemoteStatic());
            CHECK(resp.haveRemoteStatic());
            CHECK(toHex(resp.remoteStatic()) ==
                  toHex(x25519PublicKey(secretOf(v.initStatic))));
            CHECK(toHex(init.remoteStatic()) ==
                  toHex(x25519PublicKey(secretOf(v.respStatic))));

            // ---- transport messages -------------------------------------------
            CipherState initSend, initRecv, respSend, respRecv;
            CHECK(init.split(initSend, initRecv) == Status::Ok);
            CHECK(resp.split(respSend, respRecv) == Status::Ok);

            for (std::size_t i = hsCount; i < v.messageCount; ++i) {
                const bool fromInitiator = (i % 2 == 0);
                CipherState& tx = fromInitiator ? initSend : respSend;
                CipherState& rx = fromInitiator ? respRecv : initRecv;

                const auto payload  = hx(v.messages[i].payload);
                std::vector<std::uint8_t> produced;
                CHECK(tx.encryptWithAd({}, payload, produced) == Status::Ok);
                CHECK(toHex(produced) == std::string(v.messages[i].ciphertext));

                std::vector<std::uint8_t> got;
                CHECK(rx.decryptWithAd({}, produced, got) == Status::Ok);
                CHECK(got == payload);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// round trips with real, randomly generated keys
// ---------------------------------------------------------------------------

struct Peers {
    HandshakeState init, resp;
    SecretKey initS{}, respS{};
    PublicKey initPub{}, respPub{};
};

/// Drives a complete handshake. Returns Ok only if every step succeeded.
Status runHandshake(Peers& p, NoisePattern pattern,
                    std::span<const std::uint8_t> initPrologue,
                    std::span<const std::uint8_t> respPrologue)
{
    x25519KeyPair(p.initS, p.initPub);
    x25519KeyPair(p.respS, p.respPub);

    HandshakeState::Params ip;
    ip.pattern     = pattern;
    ip.initiator   = true;
    ip.prologue.assign(initPrologue.begin(), initPrologue.end());
    ip.localStatic = p.initS;
    if (pattern == NoisePattern::IK) {
        ip.remoteStatic    = p.respPub;
        ip.hasRemoteStatic = true;
    }
    if (const Status s = p.init.start(ip); s != Status::Ok) return s;

    HandshakeState::Params rp;
    rp.pattern     = pattern;
    rp.initiator   = false;
    rp.prologue.assign(respPrologue.begin(), respPrologue.end());
    rp.localStatic = p.respS;
    if (const Status s = p.resp.start(rp); s != Status::Ok) return s;

    const std::size_t count = (pattern == NoisePattern::IK) ? 2 : 3;
    for (std::size_t i = 0; i < count; ++i) {
        HandshakeState& tx = (i % 2 == 0) ? p.init : p.resp;
        HandshakeState& rx = (i % 2 == 0) ? p.resp : p.init;

        std::vector<std::uint8_t> msg;
        if (const Status s = tx.writeMessage({}, msg); s != Status::Ok) return s;

        std::vector<std::uint8_t> payload;
        if (const Status s = rx.readMessage(msg, payload); s != Status::Ok) return s;
    }
    return Status::Ok;
}

void testRoundTrips()
{
    std::printf("round trips with generated keys\n");

    const std::vector<std::uint8_t> prologue = { 'A', 'i', 'r', 'U', 'S', 'B' };

    TEST_CASE("XX completes and both sides agree on the channel binding") {
        Peers p;
        CHECK(runHandshake(p, NoisePattern::XX, prologue, prologue) == Status::Ok);
        CHECK(p.init.complete());
        CHECK(p.resp.complete());
        CHECK(p.init.handshakeHash() == p.resp.handshakeHash());
        CHECK(p.init.remoteStatic() == p.respPub);
        CHECK(p.resp.remoteStatic() == p.initPub);
    }

    TEST_CASE("IK completes in one round trip") {
        Peers p;
        CHECK(runHandshake(p, NoisePattern::IK, prologue, prologue) == Status::Ok);
        CHECK(p.init.handshakeHash() == p.resp.handshakeHash());
        CHECK(p.resp.remoteStatic() == p.initPub);
    }

    TEST_CASE("two runs with the same keys produce different transcripts") {
        // The ephemerals are fresh every time, so an observer cannot link two
        // sessions between the same pair of peers by their handshake hash.
        Peers a, b;
        CHECK(runHandshake(a, NoisePattern::XX, prologue, prologue) == Status::Ok);
        CHECK(runHandshake(b, NoisePattern::XX, prologue, prologue) == Status::Ok);
        CHECK(!(a.init.handshakeHash() == b.init.handshakeHash()));
    }

    TEST_CASE("a prologue mismatch fails the handshake") {
        // The prologue carries both peers' L0 preambles. If it were not bound,
        // an attacker could rewrite the version or the security flags in the
        // clear and the handshake would still succeed.
        const std::vector<std::uint8_t> other = { 'X' };
        Peers p;
        const Status s = runHandshake(p, NoisePattern::XX, prologue, other);
        CHECK(s != Status::Ok);
        CHECK(!p.init.complete());
    }

    TEST_CASE("an IK initiator with the wrong remote static fails") {
        SecretKey is{}, rs{}, wrong{};
        PublicKey ip{}, rp{}, wrongPub{};
        x25519KeyPair(is, ip);
        x25519KeyPair(rs, rp);
        x25519KeyPair(wrong, wrongPub);

        HandshakeState init, resp;
        HandshakeState::Params a;
        a.pattern = NoisePattern::IK;
        a.initiator = true;
        a.localStatic = is;
        a.remoteStatic = wrongPub;      // not the responder's key
        a.hasRemoteStatic = true;
        CHECK(init.start(a) == Status::Ok);

        HandshakeState::Params b;
        b.pattern = NoisePattern::IK;
        b.initiator = false;
        b.localStatic = rs;
        CHECK(resp.start(b) == Status::Ok);

        std::vector<std::uint8_t> m0;
        CHECK(init.writeMessage({}, m0) == Status::Ok);

        std::vector<std::uint8_t> got;
        // The responder mixes its own static, which differs, so the very first
        // decryption fails. This is IK's identity-hiding property working.
        CHECK(resp.readMessage(m0, got) == Status::AuthFailed);
    }
}

void testMisuseAndTampering()
{
    std::printf("misuse and tampering\n");

    const std::vector<std::uint8_t> prologue = { 'p' };

    TEST_CASE("XX must not be given a remote static, IK must be") {
        SecretKey s{};
        PublicKey p{};
        x25519KeyPair(s, p);

        HandshakeState h;
        HandshakeState::Params xxWithRs;
        xxWithRs.pattern = NoisePattern::XX;
        xxWithRs.initiator = true;
        xxWithRs.localStatic = s;
        xxWithRs.remoteStatic = p;
        xxWithRs.hasRemoteStatic = true;
        CHECK(h.start(xxWithRs) == Status::BadArgument);

        HandshakeState h2;
        HandshakeState::Params ikNoRs;
        ikNoRs.pattern = NoisePattern::IK;
        ikNoRs.initiator = true;
        ikNoRs.localStatic = s;
        CHECK(h2.start(ikNoRs) == Status::BadArgument);
    }

    TEST_CASE("writing out of turn is refused") {
        SecretKey is{}, rs{};
        PublicKey ip{}, rp{};
        x25519KeyPair(is, ip);
        x25519KeyPair(rs, rp);

        HandshakeState init;
        HandshakeState::Params a;
        a.pattern = NoisePattern::XX;
        a.initiator = true;
        a.localStatic = is;
        CHECK(init.start(a) == Status::Ok);

        std::vector<std::uint8_t> m0, m1;
        CHECK(init.writeMessage({}, m0) == Status::Ok);
        // Message 1 belongs to the responder.
        CHECK(init.writeMessage({}, m1) == Status::BadArgument);
    }

    TEST_CASE("a truncated handshake message is refused, not read past") {
        SecretKey is{}, rs{};
        PublicKey ip{}, rp{};
        x25519KeyPair(is, ip);
        x25519KeyPair(rs, rp);

        HandshakeState init, resp;
        HandshakeState::Params a;
        a.pattern = NoisePattern::XX; a.initiator = true; a.localStatic = is;
        CHECK(init.start(a) == Status::Ok);
        HandshakeState::Params b;
        b.pattern = NoisePattern::XX; b.initiator = false; b.localStatic = rs;
        CHECK(resp.start(b) == Status::Ok);

        std::vector<std::uint8_t> m0;
        CHECK(init.writeMessage({}, m0) == Status::Ok);

        for (std::size_t n = 0; n < m0.size(); ++n) {
            HandshakeState fresh;
            HandshakeState::Params c;
            c.pattern = NoisePattern::XX; c.initiator = false; c.localStatic = rs;
            CHECK(fresh.start(c) == Status::Ok);

            std::vector<std::uint8_t> got;
            const Status s = fresh.readMessage(
                std::span<const std::uint8_t>(m0).subspan(0, n), got);
            CHECK(s != Status::Ok);
        }
    }

    TEST_CASE("a tampered handshake message is AuthFailed") {
        SecretKey is{}, rs{};
        PublicKey ip{}, rp{};
        x25519KeyPair(is, ip);
        x25519KeyPair(rs, rp);

        HandshakeState init, resp;
        HandshakeState::Params a;
        a.pattern = NoisePattern::XX; a.initiator = true; a.localStatic = is;
        CHECK(init.start(a) == Status::Ok);
        HandshakeState::Params b;
        b.pattern = NoisePattern::XX; b.initiator = false; b.localStatic = rs;
        CHECK(resp.start(b) == Status::Ok);

        std::vector<std::uint8_t> m0, p0;
        CHECK(init.writeMessage({}, m0) == Status::Ok);
        CHECK(resp.readMessage(m0, p0) == Status::Ok);

        std::vector<std::uint8_t> m1;
        CHECK(resp.writeMessage({}, m1) == Status::Ok);
        m1[40] ^= 0x01u;                      // inside the encrypted static

        std::vector<std::uint8_t> p1;
        CHECK(init.readMessage(m1, p1) == Status::AuthFailed);
    }

    TEST_CASE("the test-only ephemeral hook refuses to run mid-handshake") {
        SecretKey s{}, e{};
        PublicKey p{}, ep{};
        x25519KeyPair(s, p);
        x25519KeyPair(e, ep);

        HandshakeState h;
        HandshakeState::Params a;
        a.pattern = NoisePattern::XX; a.initiator = true; a.localStatic = s;
        CHECK(h.start(a) == Status::Ok);
        CHECK(h.setFixedEphemeralForTestingOnly(e) == Status::Ok);

        std::vector<std::uint8_t> m0;
        CHECK(h.writeMessage({}, m0) == Status::Ok);
        CHECK(h.setFixedEphemeralForTestingOnly(e) == Status::BadArgument);
    }

    TEST_CASE("split before the handshake completes is refused") {
        SecretKey s{};
        PublicKey p{};
        x25519KeyPair(s, p);
        HandshakeState h;
        HandshakeState::Params a;
        a.pattern = NoisePattern::XX; a.initiator = true; a.localStatic = s;
        CHECK(h.start(a) == Status::Ok);

        CipherState tx, rx;
        CHECK(h.split(tx, rx) == Status::BadArgument);
    }
}

void testTransportProperties()
{
    std::printf("transport cipher properties\n");

    const std::vector<std::uint8_t> prologue = { 'p' };

    TEST_CASE("a forged record does not advance the nonce") {
        // Noise §5.1. If the nonce advanced on failure, a single injected byte
        // would desynchronise the stream permanently — an attacker could kill a
        // session with one forged packet even though authentication held.
        Peers p;
        CHECK(runHandshake(p, NoisePattern::XX, prologue, prologue) == Status::Ok);

        CipherState itx, irx, rtx, rrx;
        CHECK(p.init.split(itx, irx) == Status::Ok);
        CHECK(p.resp.split(rtx, rrx) == Status::Ok);

        const std::vector<std::uint8_t> msg = { 'h', 'e', 'l', 'l', 'o' };
        std::vector<std::uint8_t> sealed;
        CHECK(itx.encryptWithAd({}, msg, sealed) == Status::Ok);

        std::vector<std::uint8_t> forged = sealed;
        forged[0] ^= 0x01u;

        std::vector<std::uint8_t> out;
        CHECK_EQ(rrx.nonce(), 0ull);
        CHECK(rrx.decryptWithAd({}, forged, out) == Status::AuthFailed);
        CHECK_EQ(rrx.nonce(), 0ull);

        // The genuine record still opens.
        out.clear();
        CHECK(rrx.decryptWithAd({}, sealed, out) == Status::Ok);
        CHECK(out == msg);
        CHECK_EQ(rrx.nonce(), 1ull);
    }

    TEST_CASE("replaying a record fails — the nonce has moved on") {
        Peers p;
        CHECK(runHandshake(p, NoisePattern::XX, prologue, prologue) == Status::Ok);
        CipherState itx, irx, rtx, rrx;
        CHECK(p.init.split(itx, irx) == Status::Ok);
        CHECK(p.resp.split(rtx, rrx) == Status::Ok);

        const std::vector<std::uint8_t> a = { 1 }, b = { 2 };
        std::vector<std::uint8_t> s1, s2;
        CHECK(itx.encryptWithAd({}, a, s1) == Status::Ok);
        CHECK(itx.encryptWithAd({}, b, s2) == Status::Ok);

        std::vector<std::uint8_t> out;
        CHECK(rrx.decryptWithAd({}, s1, out) == Status::Ok);
        out.clear();
        // Replaying the first record now fails: this is why the L1 header needs
        // no sequence number.
        CHECK(rrx.decryptWithAd({}, s1, out) == Status::AuthFailed);
        out.clear();
        CHECK(rrx.decryptWithAd({}, s2, out) == Status::Ok);
    }

    TEST_CASE("records delivered out of order fail") {
        Peers p;
        CHECK(runHandshake(p, NoisePattern::XX, prologue, prologue) == Status::Ok);
        CipherState itx, irx, rtx, rrx;
        CHECK(p.init.split(itx, irx) == Status::Ok);
        CHECK(p.resp.split(rtx, rrx) == Status::Ok);

        const std::vector<std::uint8_t> a = { 1 }, b = { 2 };
        std::vector<std::uint8_t> s1, s2;
        CHECK(itx.encryptWithAd({}, a, s1) == Status::Ok);
        CHECK(itx.encryptWithAd({}, b, s2) == Status::Ok);

        std::vector<std::uint8_t> out;
        CHECK(rrx.decryptWithAd({}, s2, out) == Status::AuthFailed);
    }

    TEST_CASE("the two directions use different keys") {
        Peers p;
        CHECK(runHandshake(p, NoisePattern::XX, prologue, prologue) == Status::Ok);
        CipherState itx, irx, rtx, rrx;
        CHECK(p.init.split(itx, irx) == Status::Ok);
        CHECK(p.resp.split(rtx, rrx) == Status::Ok);

        const std::vector<std::uint8_t> msg = { 'x' };
        std::vector<std::uint8_t> sealed;
        CHECK(itx.encryptWithAd({}, msg, sealed) == Status::Ok);

        // The initiator's own receive state must NOT open what it just sent.
        // A single shared key would let an attacker reflect a peer's own
        // records back at it.
        std::vector<std::uint8_t> out;
        CHECK(irx.decryptWithAd({}, sealed, out) == Status::AuthFailed);
    }

    TEST_CASE("rekey changes the key and leaves the nonce alone") {
        Peers p;
        CHECK(runHandshake(p, NoisePattern::XX, prologue, prologue) == Status::Ok);
        CipherState itx, irx, rtx, rrx;
        CHECK(p.init.split(itx, irx) == Status::Ok);
        CHECK(p.resp.split(rtx, rrx) == Status::Ok);

        const std::vector<std::uint8_t> msg = { 'q' };
        std::vector<std::uint8_t> before;
        CHECK(itx.encryptWithAd({}, msg, before) == Status::Ok);
        const std::uint64_t n = itx.nonce();

        itx.rekey();
        CHECK_EQ(itx.nonce(), n);          // Noise: Rekey does not reset n

        std::vector<std::uint8_t> after;
        CHECK(itx.encryptWithAd({}, msg, after) == Status::Ok);
        CHECK(!(before == after));

        // The peer has not rekeyed, so it can no longer read us. Both sides
        // rekeying in step is the caller's job; this pins that it is required.
        std::vector<std::uint8_t> out;
        CHECK(rrx.decryptWithAd({}, after, out) == Status::AuthFailed);
    }

    TEST_CASE("a keyless CipherState is the identity, as Noise specifies") {
        CipherState cs;
        CHECK(!cs.hasKey());
        const std::vector<std::uint8_t> msg = { 1, 2, 3 };
        std::vector<std::uint8_t> out;
        CHECK(cs.encryptWithAd({}, msg, out) == Status::Ok);
        CHECK(out == msg);
    }

    TEST_CASE("payloads up to the Noise ceiling work, beyond it are refused") {
        Peers p;
        CHECK(runHandshake(p, NoisePattern::XX, prologue, prologue) == Status::Ok);
        CipherState itx, irx, rtx, rrx;
        CHECK(p.init.split(itx, irx) == Status::Ok);
        CHECK(p.resp.split(rtx, rrx) == Status::Ok);

        const std::vector<std::uint8_t> big(kNoiseMaxPlaintext, 0x5A);
        std::vector<std::uint8_t> sealed;
        CHECK(itx.encryptWithAd({}, big, sealed) == Status::Ok);
        CHECK_EQ(sealed.size(), kNoiseMaxMessage);

        std::vector<std::uint8_t> out;
        CHECK(rrx.decryptWithAd({}, sealed, out) == Status::Ok);
        CHECK(out.size() == big.size());
    }
}

} // namespace

int main()
{
    std::printf("test_noise\n");
    testOfficialVectors();
    testRoundTrips();
    testMisuseAndTampering();
    testTransportProperties();
    TEST_MAIN_END();
}
