// Official test vectors, extracted mechanically from the RFCs themselves.
//
// Generated by parsing the published standards, not transcribed by hand: a
// mistyped constant in a crypto test is worse than no test at all, because it
// fails loudly against correct code and passes quietly against nothing.
//
//   BLAKE2s            RFC 7693 Appendix B
//   ChaCha20-Poly1305  RFC 8439 Appendix A.5
//   X25519             RFC 7748 sections 5.2 and 6.1
//   Ed25519            RFC 8032 section 7.1
//
// The BLAKE2s digests were additionally cross-checked against OpenSSL 3 — an
// entirely separate implementation reading the same standard.

#ifndef AIRUSB_TESTS_VECTORS_CRYPTO_VECTORS_H
#define AIRUSB_TESTS_VECTORS_CRYPTO_VECTORS_H

namespace airusb::test::cryptovec {

// --- BLAKE2s-256, RFC 7693 Appendix B --------------------------------------
inline constexpr const char* kBlake2sAbcInput  = "abc";
inline constexpr const char* kBlake2sAbcDigest =
    "508c5e8c327c14e2e1a72ba34eeb452f37458b209ed63a294d999b4c86675982";
inline constexpr const char* kBlake2sEmptyDigest =
    "69217a3079908094e11121d042354a7c1f55b6482ca1a51e1b250dfd1ed0eef9";

// --- ChaCha20-Poly1305 AEAD, RFC 8439 Appendix A.5 -------------------------
//
// Chosen over the more famous section 2.8.2 vector for one reason: this one's
// nonce begins with four zero bytes, which is exactly the shape Noise mandates
// (32 bits of zeros, then a 64-bit little-endian counter). It therefore
// exercises the real aeadSeal/aeadOpen entry points rather than a test-only
// back door that takes a raw 12-byte nonce.
inline constexpr const char* kAeadKey   = "1c9240a5eb55d38af333888604f6b5f0473917c1402b80099dca5cbc207075c0";
inline constexpr const char* kAeadNonce = "000000000102030405060708";
inline constexpr unsigned long long kAeadNoiseNonce = 578437695752307201ull;
inline constexpr const char* kAeadAad   = "f33388860000000000004e91";
inline constexpr const char* kAeadTag   = "eead9d67890cbb22392336fea1851f38";
inline constexpr const char* kAeadPlaintext =
    "496e7465726e65742d4472616674732061726520647261667420646f63756d65"
    "6e74732076616c696420666f722061206d6178696d756d206f6620736978206d"
    "6f6e74687320616e64206d617920626520757064617465642c207265706c6163"
    "65642c206f72206f62736f6c65746564206279206f7468657220646f63756d65"
    "6e747320617420616e792074696d652e20497420697320696e617070726f7072"
    "6961746520746f2075736520496e7465726e65742d4472616674732061732072"
    "65666572656e6365206d6174657269616c206f7220746f206369746520746865"
    "6d206f74686572207468616e206173202fe2809c776f726b20696e2070726f67"
    "726573732e2fe2809d";
inline constexpr const char* kAeadCiphertext =
    "64a0861575861af460f062c79be643bd5e805cfd345cf389f108670ac76c8cb2"
    "4c6cfc18755d43eea09ee94e382d26b0bdb7b73c321b0100d4f03b7f355894cf"
    "332f830e710b97ce98c8a84abd0b948114ad176e008d33bd60f982b1ff37c855"
    "9797a06ef4f0ef61c186324e2b3506383606907b6a7c02b0f9f6157b53c867e4"
    "b9166c767b804d46a59b5216cde7a4e99040c5a40433225ee282a1b0a06c523e"
    "af4534d7f83fa1155b0047718cbc546a0d072b04b3564eea1b422273f548271a"
    "0bb2316053fa76991955ebd63159434ecebb4e466dae5a1073a6727627097a10"
    "49e617d91d361094fa68f0ff77987130305beaba2eda04df997b714d6c6f2c29"
    "a6ad5cb4022b02709b";

// --- X25519, RFC 7748 section 5.2 (raw scalar multiplication) --------------
inline constexpr const char* kX25519Scalar1 =
    "a546e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449ac4";
inline constexpr const char* kX25519UIn1 =
    "e6db6867583030db3594c1a424b15f7c726624ec26b3353b10a903a6d0ab1c4c";
inline constexpr const char* kX25519UOut1 =
    "c3da55379de9c6908e94ea4df28d084f32eccf03491c71f754b4075577a28552";

// --- X25519, RFC 7748 section 6.1 (a complete Diffie-Hellman exchange) -----
inline constexpr const char* kAlicePrivate =
    "77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a";
inline constexpr const char* kAlicePublic =
    "8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a";
inline constexpr const char* kBobPrivate =
    "5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb";
inline constexpr const char* kBobPublic =
    "de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f";
inline constexpr const char* kSharedSecret =
    "4a5d9d5ba4ce2de1728e3bf480350f25e07e21c947d19e3376f09b3c1e161742";

// --- Ed25519, RFC 8032 section 7.1 TEST 1 ----------------------------------
inline constexpr const char* kEdSeed =
    "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60";
inline constexpr const char* kEdPublic =
    "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a";
inline constexpr const char* kEdMessageHex = "";       // MESSAGE (length 0 bytes)
inline constexpr const char* kEdSignature =
    "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e06522490155"
    "5fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b";

} // namespace airusb::test::cryptovec

#endif // AIRUSB_TESTS_VECTORS_CRYPTO_VECTORS_H
