// Official Noise cross-implementation test vectors, extracted verbatim.
//
// Source: https://github.com/mcginty/snow  tests/vectors/cacophony.txt
// (the "cacophony" vector set, generated by an INDEPENDENT Noise
//  implementation). Only the two protocols AirUSB speaks are kept here;
//  the full file is 1.7 MB and 944 vectors.
//
// These are the single most valuable test in protocol/: they check our
// handshake against someone else's, byte for byte, including the final
// handshake hash that the SAS is derived from. A Noise implementation that
// only ever talked to itself would agree with itself perfectly while being
// wrong in a way that no self-test could reveal.

#ifndef AIRUSB_TESTS_VECTORS_NOISE_VECTORS_H
#define AIRUSB_TESTS_VECTORS_NOISE_VECTORS_H

namespace airusb::test::noisevec {

struct Message { const char* payload; const char* ciphertext; };

struct Vector {
    const char* protocolName;
    const char* initPrologue;
    const char* initStatic;
    const char* initEphemeral;
    const char* initRemoteStatic;   ///< null unless the pattern pre-shares it
    const char* respPrologue;
    const char* respStatic;
    const char* respEphemeral;
    const char* handshakeHash;
    const Message* messages;
    unsigned messageCount;
};

inline constexpr Message kMsgs0[] = {
    { "4c756477696720766f6e204d69736573", "ca35def5ae56cec33dc2036731ab14896bc4c75dbb07a61f879f8e3afa4c79440b03ddc7aac5123d06a1b23b71670e32e76c28239a7ca4ac8f784de7e44c1adbfc6e83fef7352a58d9d56157400c0a737b1d171ce368229c7b752ac25b8faf4eca690f6d896f543be02c996ab2b86b76" },
    { "4d757272617920526f746862617264", "95ebc60d2b1fa672c1f46a8aa265ef51bfe38e7ccb39ec5be34069f144808843d9b5a8927f0ac9655ef76833bc7e5561f42e691ac8404efd6fbd6308b6a27c" },
    { "462e20412e20486179656b", "2c256ed08fcd08c2980f954ee4beaccb61c9581340f5dd2fd1cf3b" },
    { "4361726c204d656e676572", "d6033f70eee20945c7c9dba304e397ee3b284ff5e00fd9efb095d3" },
    { "4a65616e2d426170746973746520536179", "a9c068ca5d8babf72560652d8e851adbfac35c8a66e810d560863173e96adf4cfe" },
    { "457567656e2042f6686d20766f6e2042617765726b", "2a09d8f459e5927e40fdd2eddc99bdafb04e13a26f145cb5cfe9e6ba34c94331ebc17d5156" },
};

inline constexpr Message kMsgs1[] = {
    { "4c756477696720766f6e204d69736573", "ca35def5ae56cec33dc2036731ab14896bc4c75dbb07a61f879f8e3afa4c79444c756477696720766f6e204d69736573" },
    { "4d757272617920526f746862617264", "95ebc60d2b1fa672c1f46a8aa265ef51bfe38e7ccb39ec5be34069f1448088437c365eb362a1c991b0557fe8a7fb187d99346765d93ec63db6c1b01504ebeec55a2298d2dbff80eff034d20595153f63a196a6cead1e11b2bb13e336fa13616dd3e8b0a070c882ed3f1a78c7c06c93" },
    { "462e20412e20486179656b", "46c3307de83b014258717d97781c1f50936d8b7d50c0722a1739654d10392d415b670c114f79b9a4f80541570f77ce88802efa4220cff733e7b5668ba38059ec904b4b8eef9448085faf51" },
    { "4361726c204d656e676572", "d5e83adfaac5dc324a68f1862df54549e56d209fba707205f328b2" },
    { "4a65616e2d426170746973746520536179", "d102c9029b1f55c788f561ba7737afbccef9c9f1bf2f238167fd40ba9c1c134867" },
    { "457567656e2042f6686d20766f6e2042617765726b", "cb1ce80960382c6d5d5e740ffb724d1432f0310b200fb6f8424120f506092744baa415e155" },
};

inline constexpr Vector kVectors[] = {
    {
        "Noise_IK_25519_ChaChaPoly_BLAKE2s",
        "4a6f686e2047616c74",
        "e61ef9919cde45dd5f82166404bd08e38bceb5dfdfded0a34c8df7ed542214d1",
        "893e28b9dc6ca8d611ab664754b8ceb7bac5117349a4439a6b0569da977c464a",
        "31e0303fd6418d2f8c0e78b91f22e8caed0fbe48656dcf4767e4834f701b8f62",
        "4a6f686e2047616c74",
        "4a3acbfdb163dec651dfa3194dece676d437029c62a408b4c5ea9114246e4893",
        "bbdb4cdbd309f1a1f2e1456967fe288cadd6f712d65dc7b7793d5e63da6b375b",
        "48f3cb8bc9319da4ba1e9933991b1c4ed4034f1f126a76d3a1fbcfd7f94248d4",
        kMsgs0, 6,
    },
    {
        "Noise_XX_25519_ChaChaPoly_BLAKE2s",
        "4a6f686e2047616c74",
        "e61ef9919cde45dd5f82166404bd08e38bceb5dfdfded0a34c8df7ed542214d1",
        "893e28b9dc6ca8d611ab664754b8ceb7bac5117349a4439a6b0569da977c464a",
        nullptr,
        "4a6f686e2047616c74",
        "4a3acbfdb163dec651dfa3194dece676d437029c62a408b4c5ea9114246e4893",
        "bbdb4cdbd309f1a1f2e1456967fe288cadd6f712d65dc7b7793d5e63da6b375b",
        "6c4c56cf71612f72d05ceb96c0155e6f4ea54a26b504c93de632a2db4a49d200",
        kMsgs1, 6,
    },
};

inline constexpr unsigned kVectorCount = 2;

} // namespace airusb::test::noisevec

#endif // AIRUSB_TESTS_VECTORS_NOISE_VECTORS_H
